# This file was autogenerated by Terraformer. DO NOT EDIT MANUALLY!

resource "github_repository_deploy_key" "api_circleci" {
  title      = "CircleCI"
  repository = "api"
  key        = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDsAoGOX44A5UYuj2VIFLOWv8BmQ6BTHE3dOOUcETrcysNcpq2Z+otRCPbJMRVPSnjAJizBnFqqzgUiIVJx4W4IxKvgni/w33UG08NML0fznkdXPKPnwQy0ldAvrmun6hif9TkY9nMfN3dsmZnyCSPNTQpDWoG8uZYxHUq26CxTq6brjAZbWAwPdw/XneC62NhhDUvxJQZCAYz3kSt28A1rwUsZmvBIoerl/OG3WEwzg3oXWfII/YfvcdcKSQyHdCytLP7IvWaGovEOtNsWB+5vIJyz8ADSxSLDxpdw7AvWhgxSsI4ocHdM8lTywnoW9EXlvUbBtH3VJw8I9cW8UkEH"
  read_only  = "True"
}

resource "github_repository_deploy_key" "charts_circleci" {
  title      = "CircleCI"
  repository = "charts"
  key        = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCiQ374qom02GlLc32MvmAJrQofXxRuH+o5F9xs4wlyZSD0Vfnq9Y2oFue07z3mZE/1awOg4shJXoZ6UFiUsRQ54944+sSIMcZXlqEf6le/rEWswq/dGPmCv1U3zEXlq/3g64HT4r162vtaC4A9rptvNKh325ovgCj6N4M7upQd+Kgf8ZWSVl1TYheWMbe6/34CykDdVWLiWjOCOK16mQrhY420ugjbBkGpa4jJHZxY1u5oPF4f3xsbuDM+cf254fB9HnKovNBGyTSqKRVmUseXRQ8ymMwPzj33niBQ1loaQYoJ+/BMJO7bUjk1Uzi5X/lDJf6O8SxR9uDS7hMTo7rp"
  read_only  = "True"
}

resource "github_repository_deploy_key" "charts_ryr-deploy-key" {
  title      = "RYR Deploy key"
  repository = "charts"
  key        = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDKV4CljZlZyXXXdcGRdJ4XMotGVsTjeDvbcIy8TdIl70Z1VUSdkQynG74FxWh43ptz+OT5nFN/OGsmSuURW68SRdGTW+X+t9sdWgvf69CgNzJZvPIhg1KgnZKSL3ht4SqmnNprdrf0eRcD8ahUjwz9XUyGOQHjPqclUSlItD6NJlwS7EXO2gATjhs/Y6SjFJcOTGJs0Q/zGqAj8b6UGReYs9S3ndAcwORl+8c9PPIHbYJBWiZYmkfNRcQqAJbNg41mCVxZ+a1EAqI/RNwzplN58bT7maBLCkE2qgxvfF14zotlVmRtP9Ri3+XFOGLDPt3FWkHgNwChaHg03BI8sMnyfZ6eTlQ1j7pyVwszfkqz8cwMXR/4IpObb6uYorlzi22Q1aX+OwVlH9sjoCoJXQA/FY7U3+JsHTR9epRsdFolPQXhsBK2QMikkzTIDI4aPqYC6CF3H/yddxB7AqECM0lxfjTbKl4W6DvVdXx6+rKHtEftyfXsUcRLfz4XiVT6JDepNehmizPwUUYq3sSBjJQ/gfMNMEkIm0bC+oF0TnyovWBIZtOkZuAxZ0hb/CnGYKjqg7SGRfxlkrOuJSugqxYKS+8D+F3aXuWA2cHI/rPfE3zNC2V2CBDUjTyDFaWs4y198s6pBXvY1jN0VApJmo63kAVsixCayr4CxNb6cIxIxQ=="
  read_only  = "False"
}

resource "github_repository_deploy_key" "docs_circleci" {
  title      = "CircleCI"
  repository = "docs"
  key        = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCQOrXr5VAesAdYHe5ty1kxCge+s+JudqYu9koVfnADysG4CqKHf0py2V7elb28Swq6fVDACnA2ID7Dd75msdNuxlCloAFbXMtiq8I9o0AqZZqqWHtE/4Z7Zzo2C4eRdj93VROHaneJpl+6Cj/r36RmTTV1tgQAvcj4kbry4/Gj48AAWSGFVUq/EAzebiGYNrfy+MVGt09ddHA2l9yIUVyQtk4Tj3Pe02EqDu+TuI+TmJzLRqUMcJcjMrMHnlXdC5PoNHz2s5w++rkj7sFIAaO5LPOiGUSvb5iOG3MXn0Py6/FCJkV0FpTR2N8uPps/nhrDXLvRapM0xee+Qy8BsOIL"
  read_only  = "True"
}

resource "github_repository_deploy_key" "docs_ryr-deploy-key" {
  title      = "RYR Deploy key"
  repository = "docs"
  key        = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDcGxRR7sLF0+6FhD1x65BC8ZWi96nEOicQdG03Gi0Z9JsgERb6SBAXcayVjANv2z0AGi5UAIbFdjlUI0STHjLO5rDWxT3hmdEtcumQ3RZPnJ5x3Fp/UKz2BRp3IcnENMrBNubPo/dIzc3s+hWxcCHUeQLJOxZV65q/WGnXoA4kssSuQGAEZCUG9rYc/aQkUZk7DxzQTTvxbxDz3LkKWSn2UYTDPsVta4sUZZ1I5QTUu/dU+hLBQEubz/8z9qe5URRxEqAht+ftppA2CnHn3fPofMPaVKrriPDTxX6JlZ6njej0z3ryAWHwRVBoqARGbbpA3XBxxnPN6j4s1sgDJSd64Mygtk3fwh7OhAwRISMgIc/9OkV5DsyB4pGjez6tOX9ZgLwyHigL+9h+ZoaYxWVxVSqF7YaXSuFRJi1h8TYbY8YPpDHbyVYh1OisiEk9CDH6B+RBaHqHfIjkai069j2yuvIC1M+t+06e3vrxC6WGQh70iRU+V3Ec9lf0bWRnt1ga6pt39XbLaoEXP9PHcdOCTd993588Wrz142fGyUZtkgjEsAOPlDE4SbQhdy8ZNh5v86wk/yCx5YLk4v9QQKHo10hGc8OHnPGxcM99tt4QYEcNQR6d9VUJtbKPhuOsKrkwNkmoK/M27MVV4LI10k6Eb2Ty0joFhSDkDYIbb3G69w=="
  read_only  = "False"
}

resource "github_repository_deploy_key" "web_circleci" {
  title      = "CircleCI"
  repository = "web"
  key        = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHuI6Egtxb2LC0LGaU+YEsmwnnldUsOh1OxAv4iEI/K/ziU7s8N5oNpTK7VnmdqSHQGG6m5uTT+BuhnwxIlkGQBEZGIC2g+csTRw3XSakEvkbpyh0FmRSP6U5MQ4yc68J4vOAmDDQ5m0Ym43aJzYMwggXUBPpk1iOubcStZCnSPrKnNEFgAgXZKw0vX7YWH7tI3IxltPkAHtfLBf3AvpLd/dmEIoZYP6dX28w6DNge8drWY1QJ3RSUFWlo0E4+C4zwCY3iBPz5Rn6cNyZ0VnMuPz6xckX1M73Rnd90OwUUv0eax0IhgyoFltZt9Eu1mfVRkKRFxsXcL9Amoxd9BY13"
  read_only  = "True"
}
