# This file was autogenerated by Terraformer. DO NOT EDIT MANUALLY!

resource "github_membership" "2echoi" {
  username = "2echoi"
  role     = "member"
}

resource "github_membership" "AndrewGibson27" {
  username = "AndrewGibson27"
  role     = "member"
}

resource "github_membership" "carenvaleria" {
  username = "carenvaleria"
  role     = "member"
}

resource "github_membership" "chanduvkp" {
  username = "chanduvkp"
  role     = "member"
}

resource "github_membership" "rgreinho" {
  username = "rgreinho"
  role     = "admin"
}

resource "github_membership" "Toughee" {
  username = "Toughee"
  role     = "member"
}

resource "github_membership" "UX-Chris" {
  username = "UX-Chris"
  role     = "member"
}
